
import React from "react";

const ROIExplanation = () => {
  return (
    <div className="w-full max-w-3xl mx-auto py-10 px-4 space-y-8 text-charcoal">
      <section className="space-y-4">
        <h2 className="text-3xl font-bold text-primary">Understanding Return on Investment (ROI)</h2>
        <p className="text-lg">
          Return on Investment (ROI) is a crucial financial metric that businesses and individuals use to evaluate the profitability 
          and efficiency of an investment. Our ROI calculator helps you make informed financial decisions by providing 
          detailed projections and visualizations of your potential returns.
        </p>
      </section>
      
      <section className="space-y-4">
        <h3 className="text-2xl font-bold text-primary">Why Calculate ROI?</h3>
        <div className="grid md:grid-cols-2 gap-6">
          <div className="bg-white p-6 rounded-lg shadow-md border-l-4 border-secondary">
            <h4 className="text-lg font-semibold mb-2">For Businesses</h4>
            <ul className="list-disc pl-5 space-y-2">
              <li>Evaluate potential projects and initiatives</li>
              <li>Compare different investment opportunities</li>
              <li>Justify budget allocations and expenditures</li>
              <li>Determine the most profitable allocation of resources</li>
              <li>Measure the success of marketing campaigns</li>
            </ul>
          </div>
          <div className="bg-white p-6 rounded-lg shadow-md border-l-4 border-accent">
            <h4 className="text-lg font-semibold mb-2">For Individuals</h4>
            <ul className="list-disc pl-5 space-y-2">
              <li>Plan retirement strategies and investments</li>
              <li>Evaluate property and real estate investments</li>
              <li>Compare different mutual funds and stocks</li>
              <li>Make informed decisions about education expenses</li>
              <li>Assess the value of major purchases and assets</li>
            </ul>
          </div>
        </div>
      </section>
      
      <section className="space-y-4">
        <h3 className="text-2xl font-bold text-primary">How Our ROI Calculator Works</h3>
        <p>
          Our comprehensive ROI calculator takes multiple factors into account to provide you with accurate and insightful projections:
        </p>
        <div className="bg-white p-6 rounded-lg shadow-md">
          <ol className="list-decimal pl-5 space-y-3">
            <li className="font-medium">
              <span className="text-primary">Initial Investment</span>: The amount you initially invest in Indian Rupees.
            </li>
            <li className="font-medium">
              <span className="text-primary">Expected Annual Return</span>: The percentage you expect to earn annually on your investment.
            </li>
            <li className="font-medium">
              <span className="text-primary">Duration</span>: The time period over which you plan to hold your investment.
            </li>
            <li className="font-medium">
              <span className="text-primary">Annual Costs</span>: Any ongoing yearly expenses associated with maintaining the investment.
            </li>
          </ol>
          <p className="mt-4">
            Based on these inputs, our calculator generates detailed metrics including total ROI, annualized ROI, 
            payback period, and projected growth over time. The visual representation helps you understand how your 
            investment is expected to grow throughout the investment period.
          </p>
        </div>
      </section>
      
      <section className="space-y-4">
        <h3 className="text-2xl font-bold text-primary">Key ROI Metrics Explained</h3>
        <div className="grid md:grid-cols-2 gap-6">
          <div className="bg-white p-5 rounded-lg shadow-md">
            <h4 className="text-lg font-semibold text-primary mb-2">Total ROI</h4>
            <p>The overall percentage return on your initial investment over the entire duration. This shows how much your investment has grown in percentage terms from start to finish.</p>
          </div>
          <div className="bg-white p-5 rounded-lg shadow-md">
            <h4 className="text-lg font-semibold text-primary mb-2">Total Return</h4>
            <p>The actual amount of profit generated by your investment, calculated after subtracting costs. This is your net gain in Indian Rupees.</p>
          </div>
          <div className="bg-white p-5 rounded-lg shadow-md">
            <h4 className="text-lg font-semibold text-primary mb-2">Annualized ROI</h4>
            <p>The average rate of return per year, which allows you to compare investments with different time horizons on an equal basis.</p>
          </div>
          <div className="bg-white p-5 rounded-lg shadow-md">
            <h4 className="text-lg font-semibold text-primary mb-2">Payback Period</h4>
            <p>The time required to recover your initial investment. A shorter payback period generally indicates a more attractive investment.</p>
          </div>
        </div>
      </section>
      
      <section className="space-y-4">
        <h3 className="text-2xl font-bold text-primary">Making the Most of Your ROI Analysis</h3>
        <div className="bg-primary/5 p-6 rounded-lg border border-primary/20">
          <p className="mb-4">
            To maximize the value of your ROI calculations, consider these best practices:
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li><span className="font-medium">Be realistic with projections</span>: Use historical data and industry benchmarks to set reasonable expectations.</li>
            <li><span className="font-medium">Include all costs</span>: Account for maintenance, taxes, inflation, and other expenses that might affect your true return.</li>
            <li><span className="font-medium">Run multiple scenarios</span>: Try different inputs to understand best-case, worst-case, and most likely outcomes.</li>
            <li><span className="font-medium">Reassess periodically</span>: Review your investment performance against projections and adjust your strategy as needed.</li>
            <li><span className="font-medium">Consider qualitative factors</span>: Some benefits like brand awareness or employee satisfaction may not be directly measurable but still impact overall ROI.</li>
          </ul>
        </div>
      </section>
      
      <section className="mt-10 space-y-4">
        <h3 className="text-2xl font-bold text-primary">Download and Share Your Results</h3>
        <p>
          Our calculator allows you to save and share your ROI analysis in multiple ways:
        </p>
        <div className="grid md:grid-cols-2 gap-6">
          <div className="bg-white p-6 rounded-lg shadow-md border-t-4 border-accent">
            <h4 className="text-lg font-semibold mb-2">PDF Report</h4>
            <p>Download a professionally formatted PDF report containing all your input parameters, calculated metrics, and visualizations. Perfect for presentations, record-keeping, or sharing with stakeholders.</p>
          </div>
          <div className="bg-white p-6 rounded-lg shadow-md border-t-4 border-chatbot">
            <h4 className="text-lg font-semibold mb-2">Email Results</h4>
            <p>Send the detailed analysis directly to your email or share it with colleagues, clients, or financial advisors. The email includes all the key metrics and a PDF attachment of the full report.</p>
          </div>
        </div>
      </section>
      
      <section className="mt-8 bg-white p-6 rounded-lg shadow-md">
        <h3 className="text-2xl font-bold text-primary mb-4">Start Your ROI Analysis Today</h3>
        <p className="mb-2">
          Whether you're a business owner evaluating a new project, an investor comparing opportunities, or an individual planning your financial future, our ROI calculator provides the insights you need to make confident decisions.
        </p>
        <p>
          Enter your investment details above to get started, and discover the potential returns waiting for you. Use the visualization tools to better understand growth patterns, and don't forget to download or email your results for future reference.
        </p>
      </section>
    </div>
  );
};

export default ROIExplanation;
